export const DEFAULT_LANGUAGE = "en-US";

export const LANGUAGE_OPTIONS = [
  { id: "en-US", label: "English", nativeLabel: "English" },
  { id: "zh-CN", label: "Mandarin", nativeLabel: "中文" },
  { id: "ko-KR", label: "Korean", nativeLabel: "한국어" },
  { id: "ja-JP", label: "Japanese", nativeLabel: "日本語" },
  { id: "es-ES", label: "Spanish", nativeLabel: "Español" },
  { id: "ru-RU", label: "Russian", nativeLabel: "Русский" },
  { id: "pt-BR", label: "Portuguese", nativeLabel: "Português" },
];

const LANGUAGE_IDS = new Set(LANGUAGE_OPTIONS.map((option) => option.id));
const LANGUAGE_STORAGE_KEY = "guidegpt:language:v1";

const copy = {
  "en-US": {
    onPage: "On this page",
    demoMode: "Demo mode",
    connecting: "Connecting…",
    customize: "Customize GuideGPT",
    minimize: "Minimize GuideGPT",
    close: "Close GuideGPT",
    makeYours: "Make it yours",
    dragResize: "Drag anywhere. Resize to any ratio.",
    windowColor: "Window color",
    resetWindow: "Reset size and position",
    language: "Language",
    voiceOn: "Voice-over on",
    voiceOff: "Voice-over off",
    voiceUnavailable: "Voice input is unavailable in this browser. You can still type your question.",
    voiceOverUnavailable: "Voice-over is unavailable in this browser.",
    voiceError: "I couldn’t hear that. Check microphone permission and try again.",
    microphone: "Talk to GuideGPT",
    stopListening: "Stop listening",
    listening: "Listening… speak naturally",
    transcribing: "Turning your voice into text…",
    transcriptReady: "Transcript ready—review it, then send.",
    privateBrowser: "Private to this browser",
    missionHistory: "Mission history",
    noMissions: "No missions yet",
    savedGuides: "Your saved guides will appear here.",
    clearHistoryPrompt: "Clear all private mission history?",
    cancel: "Cancel",
    clear: "Clear",
    clearHistory: "Clear history",
    back: "Back to GuideGPT",
    guidePlan: "Guide plan",
    preparingStep: "Preparing the next step",
    step: "Step {current} of {total}",
    stepProgress: "{current} of {total} steps",
    showMe: "Show me",
    done: "Done",
    currentStep: "Current GuideGPT step",
    missionComplete: "Mission complete.",
    finished: "You finished every step in this guide.",
    prompt: "Tell me what you want to accomplish and I’ll guide you one safe step at a time.",
    privacyTitle: "Privacy first.",
    privacyBody: "I use visible page content. The mic starts only when tapped; your browser or our transcription provider processes the audio, then you review the transcript before it becomes a GuideGPT request.",
    reading: "Reading the visible page and building your guide…",
    visiblePage: "Visible page",
    placeholder: "Ask about this screen or start a new guide…",
    composerLabel: "Ask GuideGPT about this page",
    send: "Send to GuideGPT",
    open: "Open GuideGPT",
    assistantLabel: "GuideGPT assistant",
    dragWindow: "Drag GuideGPT window",
    dragWindowHint: "Drag window · Arrow keys also move it",
    customizerRegion: "Customize GuideGPT window",
    useColor: "Use {theme} color",
    responseActions: "Response actions",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    copyGuide: "Copy guide",
    copied: "Copied",
    copyFailed: "Couldn’t copy",
    resizeWindow: "Resize GuideGPT window",
    resizeWindowHint: "Drag to resize · Arrow keys also resize",
    connectingError: "The live guide is still connecting. You can explore the built-in installation walkthrough meanwhile.",
    preparingSafePlan: "Reading this page and preparing a safe plan.",
    highlightError: "That control is not visible on this page right now.",
    statusActive: "Active",
    statusPaused: "Paused",
    statusCompleted: "Completed",
    basicGuide: "Basic guide",
    untitledPage: "Untitled page",
  },
  "zh-CN": {
    onPage: "正在查看此页面",
    demoMode: "演示模式",
    connecting: "正在连接…",
    customize: "自定义 GuideGPT",
    minimize: "最小化 GuideGPT",
    close: "关闭 GuideGPT",
    makeYours: "按你的方式设置",
    dragResize: "可自由拖动，并调整为任意比例。",
    windowColor: "窗口颜色",
    resetWindow: "重置大小和位置",
    language: "语言",
    voiceOn: "语音播报已开启",
    voiceOff: "语音播报已关闭",
    voiceUnavailable: "此浏览器不支持语音输入，你仍可以输入问题。",
    voiceOverUnavailable: "此浏览器不支持语音播报。",
    voiceError: "没有听清。请检查麦克风权限后重试。",
    microphone: "与 GuideGPT 对话",
    stopListening: "停止聆听",
    listening: "正在聆听…请自然说话",
    transcribing: "正在将语音转换成文字…",
    transcriptReady: "语音已转成文字，请确认后发送。",
    privateBrowser: "仅保存在此浏览器中",
    missionHistory: "任务记录",
    noMissions: "还没有任务",
    savedGuides: "保存的指南会显示在这里。",
    clearHistoryPrompt: "清除所有私人任务记录？",
    cancel: "取消",
    clear: "清除",
    clearHistory: "清除记录",
    back: "返回 GuideGPT",
    guidePlan: "指导计划",
    preparingStep: "正在准备下一步",
    step: "第 {current} 步，共 {total} 步",
    stepProgress: "{current}/{total} 步",
    showMe: "指给我看",
    done: "完成",
    currentStep: "GuideGPT 当前步骤",
    missionComplete: "任务已完成。",
    finished: "你已完成本指南的所有步骤。",
    prompt: "告诉我你想完成什么，我会一步一步安全地指导你。",
    privacyTitle: "隐私优先。",
    privacyBody: "我使用页面上的可见内容。麦克风只会在你点击后开启；浏览器或我们的转录服务商会处理音频，转录文字会先供你检查，发送后才会成为 GuideGPT 请求。",
    reading: "正在读取可见页面并创建指南…",
    visiblePage: "可见页面",
    placeholder: "询问此屏幕，或开始新的指南…",
    composerLabel: "向 GuideGPT 询问此页面",
    send: "发送给 GuideGPT",
    open: "打开 GuideGPT",
    assistantLabel: "GuideGPT 助手",
    dragWindow: "拖动 GuideGPT 窗口",
    dragWindowHint: "拖动窗口 · 也可使用方向键移动",
    customizerRegion: "自定义 GuideGPT 窗口",
    useColor: "使用{theme}颜色",
    responseActions: "回复操作",
    helpful: "有帮助",
    notHelpful: "没有帮助",
    copyGuide: "复制指南",
    copied: "已复制",
    copyFailed: "复制失败",
    resizeWindow: "调整 GuideGPT 窗口大小",
    resizeWindowHint: "拖动调整大小 · 也可使用方向键",
    connectingError: "实时指南仍在连接。你可以先查看内置的安装演示。",
    preparingSafePlan: "正在读取此页面并准备安全的计划。",
    highlightError: "当前页面上看不到该控件。",
    statusActive: "进行中",
    statusPaused: "已暂停",
    statusCompleted: "已完成",
    basicGuide: "基础指南",
    untitledPage: "未命名页面",
  },
  "ko-KR": {
    onPage: "이 페이지를 보는 중",
    demoMode: "데모 모드",
    connecting: "연결 중…",
    customize: "GuideGPT 맞춤 설정",
    minimize: "GuideGPT 최소화",
    close: "GuideGPT 닫기",
    makeYours: "내게 맞게 설정",
    dragResize: "자유롭게 옮기고 원하는 비율로 조절하세요.",
    windowColor: "창 색상",
    resetWindow: "크기와 위치 초기화",
    language: "언어",
    voiceOn: "음성 안내 켜짐",
    voiceOff: "음성 안내 꺼짐",
    voiceUnavailable: "이 브라우저에서는 음성 입력을 사용할 수 없습니다. 질문을 입력할 수 있습니다.",
    voiceOverUnavailable: "이 브라우저에서는 음성 안내를 사용할 수 없습니다.",
    voiceError: "잘 듣지 못했습니다. 마이크 권한을 확인하고 다시 시도하세요.",
    microphone: "GuideGPT와 말하기",
    stopListening: "듣기 중지",
    listening: "듣고 있어요…자연스럽게 말씀하세요",
    transcribing: "음성을 글로 바꾸는 중…",
    transcriptReady: "음성이 글로 변환되었습니다. 확인 후 보내세요.",
    privateBrowser: "이 브라우저에만 저장",
    missionHistory: "가이드 기록",
    noMissions: "아직 가이드가 없습니다",
    savedGuides: "저장한 가이드가 여기에 표시됩니다.",
    clearHistoryPrompt: "모든 비공개 가이드 기록을 지울까요?",
    cancel: "취소",
    clear: "지우기",
    clearHistory: "기록 지우기",
    back: "GuideGPT로 돌아가기",
    guidePlan: "가이드 계획",
    preparingStep: "다음 단계 준비 중",
    step: "{total}단계 중 {current}단계",
    stepProgress: "{total}단계 중 {current}",
    showMe: "위치 보기",
    done: "완료",
    currentStep: "현재 GuideGPT 단계",
    missionComplete: "가이드를 완료했습니다.",
    finished: "이 가이드의 모든 단계를 완료했습니다.",
    prompt: "원하는 일을 말씀해 주세요. 안전하게 한 단계씩 안내하겠습니다.",
    privacyTitle: "개인정보 보호 우선.",
    privacyBody: "화면에 보이는 내용만 사용합니다. 마이크는 눌렀을 때만 켜지고 브라우저 또는 전사 서비스가 음성을 처리합니다. 변환된 글은 GuideGPT 요청이 되기 전에 확인할 수 있습니다.",
    reading: "보이는 화면을 읽고 가이드를 만드는 중…",
    visiblePage: "보이는 페이지",
    placeholder: "이 화면에 대해 묻거나 새 가이드를 시작하세요…",
    composerLabel: "이 페이지에 대해 GuideGPT에 질문하기",
    send: "GuideGPT에 보내기",
    open: "GuideGPT 열기",
    assistantLabel: "GuideGPT 도우미",
    dragWindow: "GuideGPT 창 이동",
    dragWindowHint: "창을 드래그하세요 · 화살표 키로도 이동할 수 있습니다",
    customizerRegion: "GuideGPT 창 맞춤 설정",
    useColor: "{theme} 색상 사용",
    responseActions: "응답 작업",
    helpful: "도움이 됨",
    notHelpful: "도움이 안 됨",
    copyGuide: "가이드 복사",
    copied: "복사됨",
    copyFailed: "복사하지 못함",
    resizeWindow: "GuideGPT 창 크기 조절",
    resizeWindowHint: "드래그하여 크기 조절 · 화살표 키로도 조절할 수 있습니다",
    connectingError: "실시간 가이드에 연결 중입니다. 그동안 기본 설치 안내를 살펴볼 수 있습니다.",
    preparingSafePlan: "이 페이지를 읽고 안전한 계획을 준비하고 있습니다.",
    highlightError: "현재 이 페이지에서 해당 컨트롤을 볼 수 없습니다.",
    statusActive: "진행 중",
    statusPaused: "일시 중지",
    statusCompleted: "완료",
    basicGuide: "기본 가이드",
    untitledPage: "제목 없는 페이지",
  },
  "ja-JP": {
    onPage: "このページを確認中",
    demoMode: "デモモード",
    connecting: "接続中…",
    customize: "GuideGPTをカスタマイズ",
    minimize: "GuideGPTを最小化",
    close: "GuideGPTを閉じる",
    makeYours: "使いやすく設定",
    dragResize: "自由に移動し、好きな比率に変更できます。",
    windowColor: "ウィンドウの色",
    resetWindow: "サイズと位置をリセット",
    language: "言語",
    voiceOn: "読み上げオン",
    voiceOff: "読み上げオフ",
    voiceUnavailable: "このブラウザでは音声入力を利用できません。文字入力は利用できます。",
    voiceOverUnavailable: "このブラウザでは読み上げを利用できません。",
    voiceError: "聞き取れませんでした。マイクの許可を確認して、もう一度お試しください。",
    microphone: "GuideGPTに話す",
    stopListening: "聞き取りを停止",
    listening: "聞いています…自然に話してください",
    transcribing: "音声を文字に変換しています…",
    transcriptReady: "音声を文字にしました。確認してから送信してください。",
    privateBrowser: "このブラウザ内だけで保存",
    missionHistory: "ガイド履歴",
    noMissions: "ガイドはまだありません",
    savedGuides: "保存したガイドがここに表示されます。",
    clearHistoryPrompt: "すべての非公開ガイド履歴を消去しますか？",
    cancel: "キャンセル",
    clear: "消去",
    clearHistory: "履歴を消去",
    back: "GuideGPTに戻る",
    guidePlan: "ガイド手順",
    preparingStep: "次の手順を準備中",
    step: "{total}ステップ中 {current}",
    stepProgress: "{total}ステップ中 {current}",
    showMe: "場所を表示",
    done: "完了",
    currentStep: "現在のGuideGPT手順",
    missionComplete: "ガイドが完了しました。",
    finished: "このガイドのすべての手順が完了しました。",
    prompt: "やりたいことを教えてください。安全に一つずつご案内します。",
    privacyTitle: "プライバシーを優先。",
    privacyBody: "画面に表示されている内容を使用します。マイクはタップしたときだけ起動し、ブラウザまたは文字起こしサービスが音声を処理します。GuideGPTへの依頼になる前に文字を確認できます。",
    reading: "表示中の画面を読み取り、ガイドを作成しています…",
    visiblePage: "表示中のページ",
    placeholder: "この画面について質問するか、新しいガイドを始める…",
    composerLabel: "このページについてGuideGPTに質問",
    send: "GuideGPTに送信",
    open: "GuideGPTを開く",
    assistantLabel: "GuideGPTアシスタント",
    dragWindow: "GuideGPTウィンドウを移動",
    dragWindowHint: "ドラッグして移動 · 矢印キーでも移動できます",
    customizerRegion: "GuideGPTウィンドウをカスタマイズ",
    useColor: "{theme}カラーを使用",
    responseActions: "回答の操作",
    helpful: "役に立った",
    notHelpful: "役に立たなかった",
    copyGuide: "ガイドをコピー",
    copied: "コピーしました",
    copyFailed: "コピーできませんでした",
    resizeWindow: "GuideGPTウィンドウのサイズを変更",
    resizeWindowHint: "ドラッグしてサイズ変更 · 矢印キーでも変更できます",
    connectingError: "ライブガイドに接続中です。その間、内蔵のインストールガイドをお試しください。",
    preparingSafePlan: "このページを読み取り、安全なプランを準備しています。",
    highlightError: "その操作項目は現在このページに表示されていません。",
    statusActive: "進行中",
    statusPaused: "一時停止",
    statusCompleted: "完了",
    basicGuide: "基本ガイド",
    untitledPage: "無題のページ",
  },
  "es-ES": {
    onPage: "En esta página",
    demoMode: "Modo de demostración",
    connecting: "Conectando…",
    customize: "Personalizar GuideGPT",
    minimize: "Minimizar GuideGPT",
    close: "Cerrar GuideGPT",
    makeYours: "Hazlo a tu manera",
    dragResize: "Muévelo y cambia su tamaño a cualquier proporción.",
    windowColor: "Color de la ventana",
    resetWindow: "Restablecer tamaño y posición",
    language: "Idioma",
    voiceOn: "Lectura en voz alta activada",
    voiceOff: "Lectura en voz alta desactivada",
    voiceUnavailable: "La entrada de voz no está disponible en este navegador. Aún puedes escribir.",
    voiceOverUnavailable: "La lectura en voz alta no está disponible en este navegador.",
    voiceError: "No pude oírte. Revisa el permiso del micrófono e inténtalo de nuevo.",
    microphone: "Hablar con GuideGPT",
    stopListening: "Dejar de escuchar",
    listening: "Escuchando… habla con naturalidad",
    transcribing: "Convirtiendo tu voz en texto…",
    transcriptReady: "La transcripción está lista. Revísala y envíala.",
    privateBrowser: "Privado en este navegador",
    missionHistory: "Historial de guías",
    noMissions: "Todavía no hay guías",
    savedGuides: "Tus guías guardadas aparecerán aquí.",
    clearHistoryPrompt: "¿Borrar todo el historial privado?",
    cancel: "Cancelar",
    clear: "Borrar",
    clearHistory: "Borrar historial",
    back: "Volver a GuideGPT",
    guidePlan: "Plan de guía",
    preparingStep: "Preparando el siguiente paso",
    step: "Paso {current} de {total}",
    stepProgress: "{current} de {total} pasos",
    showMe: "Muéstrame",
    done: "Listo",
    currentStep: "Paso actual de GuideGPT",
    missionComplete: "Guía completada.",
    finished: "Completaste todos los pasos de esta guía.",
    prompt: "Dime qué quieres hacer y te guiaré de forma segura, paso a paso.",
    privacyTitle: "Privacidad primero.",
    privacyBody: "Uso el contenido visible. El micrófono solo se activa al tocarlo; tu navegador o nuestro proveedor procesa el audio y revisas la transcripción antes de que se convierta en una solicitud para GuideGPT.",
    reading: "Leyendo la pantalla visible y creando tu guía…",
    visiblePage: "Página visible",
    placeholder: "Pregunta sobre esta pantalla o inicia una guía nueva…",
    composerLabel: "Preguntar a GuideGPT sobre esta página",
    send: "Enviar a GuideGPT",
    open: "Abrir GuideGPT",
    assistantLabel: "Asistente de GuideGPT",
    dragWindow: "Mover la ventana de GuideGPT",
    dragWindowHint: "Arrastra la ventana · También puedes moverla con las flechas",
    customizerRegion: "Personalizar la ventana de GuideGPT",
    useColor: "Usar el color {theme}",
    responseActions: "Acciones de respuesta",
    helpful: "Útil",
    notHelpful: "No útil",
    copyGuide: "Copiar guía",
    copied: "Copiada",
    copyFailed: "No se pudo copiar",
    resizeWindow: "Cambiar el tamaño de GuideGPT",
    resizeWindowHint: "Arrastra para cambiar el tamaño · También puedes usar las flechas",
    connectingError: "La guía en vivo aún se está conectando. Mientras tanto, puedes explorar el recorrido de instalación incluido.",
    preparingSafePlan: "Leyendo esta página y preparando un plan seguro.",
    highlightError: "Ese control no está visible en esta página ahora mismo.",
    statusActive: "Activa",
    statusPaused: "En pausa",
    statusCompleted: "Completada",
    basicGuide: "Guía básica",
    untitledPage: "Página sin título",
  },
  "ru-RU": {
    onPage: "На этой странице",
    demoMode: "Демо-режим",
    connecting: "Подключение…",
    customize: "Настроить GuideGPT",
    minimize: "Свернуть GuideGPT",
    close: "Закрыть GuideGPT",
    makeYours: "Настройте под себя",
    dragResize: "Перемещайте и меняйте размер в любых пропорциях.",
    windowColor: "Цвет окна",
    resetWindow: "Сбросить размер и положение",
    language: "Язык",
    voiceOn: "Озвучивание включено",
    voiceOff: "Озвучивание выключено",
    voiceUnavailable: "Голосовой ввод недоступен в этом браузере. Вы по-прежнему можете печатать.",
    voiceOverUnavailable: "Озвучивание недоступно в этом браузере.",
    voiceError: "Я не расслышал. Проверьте доступ к микрофону и попробуйте снова.",
    microphone: "Говорить с GuideGPT",
    stopListening: "Остановить прослушивание",
    listening: "Слушаю…говорите естественно",
    transcribing: "Преобразую речь в текст…",
    transcriptReady: "Текст готов. Проверьте его и отправьте.",
    privateBrowser: "Доступно только в этом браузере",
    missionHistory: "История инструкций",
    noMissions: "Инструкций пока нет",
    savedGuides: "Сохранённые инструкции появятся здесь.",
    clearHistoryPrompt: "Очистить всю личную историю?",
    cancel: "Отмена",
    clear: "Очистить",
    clearHistory: "Очистить историю",
    back: "Вернуться к GuideGPT",
    guidePlan: "План действий",
    preparingStep: "Готовлю следующий шаг",
    step: "Шаг {current} из {total}",
    stepProgress: "{current} из {total} шагов",
    showMe: "Показать",
    done: "Готово",
    currentStep: "Текущий шаг GuideGPT",
    missionComplete: "Инструкция выполнена.",
    finished: "Вы выполнили все шаги этой инструкции.",
    prompt: "Скажите, что вы хотите сделать, и я безопасно проведу вас по шагам.",
    privacyTitle: "Конфиденциальность прежде всего.",
    privacyBody: "Я использую только видимое содержимое. Микрофон включается после нажатия; браузер или наш сервис транскрипции обрабатывает аудио, а вы проверяете текст до отправки запроса в GuideGPT.",
    reading: "Читаю видимую часть экрана и составляю инструкцию…",
    visiblePage: "Видимая страница",
    placeholder: "Спросите об этом экране или начните новую инструкцию…",
    composerLabel: "Спросить GuideGPT об этой странице",
    send: "Отправить в GuideGPT",
    open: "Открыть GuideGPT",
    assistantLabel: "Помощник GuideGPT",
    dragWindow: "Переместить окно GuideGPT",
    dragWindowHint: "Перетащите окно · Его также можно перемещать стрелками",
    customizerRegion: "Настроить окно GuideGPT",
    useColor: "Использовать цвет «{theme}»",
    responseActions: "Действия с ответом",
    helpful: "Полезно",
    notHelpful: "Не полезно",
    copyGuide: "Копировать инструкцию",
    copied: "Скопировано",
    copyFailed: "Не удалось скопировать",
    resizeWindow: "Изменить размер окна GuideGPT",
    resizeWindowHint: "Перетащите для изменения размера · Также можно использовать стрелки",
    connectingError: "Живой помощник всё ещё подключается. Пока можно посмотреть встроенную инструкцию по установке.",
    preparingSafePlan: "Читаю эту страницу и готовлю безопасный план.",
    highlightError: "Этот элемент сейчас не виден на странице.",
    statusActive: "Активна",
    statusPaused: "Приостановлена",
    statusCompleted: "Завершена",
    basicGuide: "Базовая инструкция",
    untitledPage: "Страница без названия",
  },
  "pt-BR": {
    onPage: "Nesta página",
    demoMode: "Modo de demonstração",
    connecting: "Conectando…",
    customize: "Personalizar o GuideGPT",
    minimize: "Minimizar o GuideGPT",
    close: "Fechar o GuideGPT",
    makeYours: "Deixe do seu jeito",
    dragResize: "Mova e redimensione para qualquer proporção.",
    windowColor: "Cor da janela",
    resetWindow: "Redefinir tamanho e posição",
    language: "Idioma",
    voiceOn: "Narração ativada",
    voiceOff: "Narração desativada",
    voiceUnavailable: "A entrada de voz não está disponível neste navegador. Você ainda pode digitar.",
    voiceOverUnavailable: "A narração não está disponível neste navegador.",
    voiceError: "Não consegui ouvir. Verifique a permissão do microfone e tente novamente.",
    microphone: "Falar com o GuideGPT",
    stopListening: "Parar de ouvir",
    listening: "Ouvindo…fale naturalmente",
    transcribing: "Transformando sua voz em texto…",
    transcriptReady: "A transcrição está pronta. Revise e envie.",
    privateBrowser: "Privado neste navegador",
    missionHistory: "Histórico de guias",
    noMissions: "Ainda não há guias",
    savedGuides: "Seus guias salvos aparecerão aqui.",
    clearHistoryPrompt: "Limpar todo o histórico privado?",
    cancel: "Cancelar",
    clear: "Limpar",
    clearHistory: "Limpar histórico",
    back: "Voltar ao GuideGPT",
    guidePlan: "Plano de orientação",
    preparingStep: "Preparando o próximo passo",
    step: "Passo {current} de {total}",
    stepProgress: "{current} de {total} passos",
    showMe: "Mostre-me",
    done: "Concluído",
    currentStep: "Passo atual do GuideGPT",
    missionComplete: "Guia concluído.",
    finished: "Você concluiu todas as etapas deste guia.",
    prompt: "Diga o que você quer fazer e eu orientarei você com segurança, passo a passo.",
    privacyTitle: "Privacidade em primeiro lugar.",
    privacyBody: "Uso o conteúdo visível. O microfone só inicia quando você toca nele; seu navegador ou nosso provedor processa o áudio, e você revisa a transcrição antes que ela se torne uma solicitação ao GuideGPT.",
    reading: "Lendo a tela visível e criando seu guia…",
    visiblePage: "Página visível",
    placeholder: "Pergunte sobre esta tela ou inicie um novo guia…",
    composerLabel: "Perguntar ao GuideGPT sobre esta página",
    send: "Enviar ao GuideGPT",
    open: "Abrir o GuideGPT",
    assistantLabel: "Assistente do GuideGPT",
    dragWindow: "Mover a janela do GuideGPT",
    dragWindowHint: "Arraste a janela · As setas também podem movê-la",
    customizerRegion: "Personalizar a janela do GuideGPT",
    useColor: "Usar a cor {theme}",
    responseActions: "Ações da resposta",
    helpful: "Útil",
    notHelpful: "Não foi útil",
    copyGuide: "Copiar guia",
    copied: "Copiado",
    copyFailed: "Não foi possível copiar",
    resizeWindow: "Redimensionar a janela do GuideGPT",
    resizeWindowHint: "Arraste para redimensionar · As setas também redimensionam",
    connectingError: "O guia ao vivo ainda está se conectando. Enquanto isso, você pode explorar o passo a passo de instalação incluído.",
    preparingSafePlan: "Lendo esta página e preparando um plano seguro.",
    highlightError: "Esse controle não está visível nesta página agora.",
    statusActive: "Ativa",
    statusPaused: "Pausada",
    statusCompleted: "Concluída",
    basicGuide: "Guia básico",
    untitledPage: "Página sem título",
  },
};

export const TRANSLATION_KEYS = Object.freeze(Object.keys(copy[DEFAULT_LANGUAGE]).sort());

export function localizedCopyKeys(language) {
  const normalized = normalizeLanguage(language);
  return Object.keys(copy[normalized] || {}).sort();
}

const demoCopy = {
  "en-US": {
    goal: "Help me install GuideGPT and start my first guide.",
    summary: "I can help with that. Here’s the quickest way to get GuideGPT ready:",
    steps: [
      ["Install the Chrome extension", "Select “Install extension” to download GuideGPT for Chrome."],
      ["Add GuideGPT to Chrome", "Unzip the download, open Chrome extensions, enable Developer mode, then choose Load unpacked."],
      ["Start your first guide", "Open GuideGPT on a website and describe the outcome you want in your own words."],
    ],
  },
  "zh-CN": {
    goal: "帮我安装 GuideGPT，并开始第一个指南。",
    summary: "没问题。最快可以这样开始使用 GuideGPT：",
    steps: [
      ["安装 Chrome 扩展程序", "选择“安装扩展程序”，下载 Chrome 版 GuideGPT。"],
      ["将 GuideGPT 添加到 Chrome", "解压下载文件，打开 Chrome 扩展程序页面，开启开发者模式，然后选择“加载已解压的扩展程序”。"],
      ["开始第一个指南", "在网站上打开 GuideGPT，用自己的话描述你想完成的事情。"],
    ],
  },
  "ko-KR": {
    goal: "GuideGPT를 설치하고 첫 가이드를 시작하도록 도와주세요.",
    summary: "도와드릴게요. GuideGPT를 가장 빠르게 시작하는 방법입니다:",
    steps: [
      ["Chrome 확장 프로그램 설치", "‘Install extension’을 선택하여 Chrome용 GuideGPT를 다운로드하세요."],
      ["Chrome에 GuideGPT 추가", "다운로드 파일의 압축을 풀고 Chrome 확장 프로그램을 연 뒤 개발자 모드를 켜고 ‘압축해제된 확장 프로그램을 로드합니다’를 선택하세요."],
      ["첫 가이드 시작", "웹사이트에서 GuideGPT를 열고 원하는 결과를 편한 말로 설명하세요."],
    ],
  },
  "ja-JP": {
    goal: "GuideGPTをインストールして、最初のガイドを始めたいです。",
    summary: "お手伝いします。GuideGPTを最短で使い始める手順はこちらです：",
    steps: [
      ["Chrome拡張機能をインストール", "「Install extension」を選んでChrome版GuideGPTをダウンロードします。"],
      ["GuideGPTをChromeに追加", "ダウンロードを解凍し、Chromeの拡張機能を開き、デベロッパーモードをオンにして「パッケージ化されていない拡張機能を読み込む」を選びます。"],
      ["最初のガイドを開始", "ウェブサイトでGuideGPTを開き、やりたいことを自分の言葉で説明します。"],
    ],
  },
  "es-ES": {
    goal: "Ayúdame a instalar GuideGPT y empezar mi primera guía.",
    summary: "Claro. Esta es la forma más rápida de preparar GuideGPT:",
    steps: [
      ["Instala la extensión de Chrome", "Selecciona “Install extension” para descargar GuideGPT para Chrome."],
      ["Añade GuideGPT a Chrome", "Descomprime la descarga, abre las extensiones de Chrome, activa el modo de desarrollador y selecciona Cargar descomprimida."],
      ["Inicia tu primera guía", "Abre GuideGPT en un sitio web y explica con tus propias palabras lo que quieres conseguir."],
    ],
  },
  "ru-RU": {
    goal: "Помогите установить GuideGPT и начать первую инструкцию.",
    summary: "Конечно. Вот самый быстрый способ подготовить GuideGPT:",
    steps: [
      ["Установите расширение Chrome", "Выберите «Install extension», чтобы скачать GuideGPT для Chrome."],
      ["Добавьте GuideGPT в Chrome", "Распакуйте загрузку, откройте расширения Chrome, включите режим разработчика и выберите «Загрузить распакованное расширение»."],
      ["Начните первую инструкцию", "Откройте GuideGPT на сайте и своими словами опишите желаемый результат."],
    ],
  },
  "pt-BR": {
    goal: "Ajude-me a instalar o GuideGPT e iniciar meu primeiro guia.",
    summary: "Claro. Esta é a maneira mais rápida de preparar o GuideGPT:",
    steps: [
      ["Instale a extensão do Chrome", "Selecione “Install extension” para baixar o GuideGPT para Chrome."],
      ["Adicione o GuideGPT ao Chrome", "Descompacte o download, abra as extensões do Chrome, ative o modo de desenvolvedor e selecione Carregar sem compactação."],
      ["Inicie seu primeiro guia", "Abra o GuideGPT em um site e descreva com suas próprias palavras o resultado desejado."],
    ],
  },
};

export function normalizeLanguage(value) {
  if (value === "en") return DEFAULT_LANGUAGE;
  return LANGUAGE_IDS.has(value) ? value : DEFAULT_LANGUAGE;
}

export function languageOption(value) {
  const normalized = normalizeLanguage(value);
  return LANGUAGE_OPTIONS.find((option) => option.id === normalized) || LANGUAGE_OPTIONS[0];
}

export function localizedDemoCopy(value) {
  const normalized = normalizeLanguage(value);
  return demoCopy[normalized] || demoCopy[DEFAULT_LANGUAGE];
}

export function t(language, key, values = {}) {
  const normalized = normalizeLanguage(language);
  const template = copy[normalized]?.[key] || copy[DEFAULT_LANGUAGE]?.[key] || key;
  return Object.entries(values).reduce(
    (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

export function readLanguagePreference() {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;
  try {
    return normalizeLanguage(window.localStorage.getItem(LANGUAGE_STORAGE_KEY));
  } catch {
    return DEFAULT_LANGUAGE;
  }
}

export function persistLanguagePreference(language) {
  const normalized = normalizeLanguage(language);
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, normalized);
    } catch {
      // The current session still uses the chosen language when storage is blocked.
    }
  }
  return normalized;
}
